name: Docsify site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
   first_job:
    name: My first job
    runs-on: ubuntu-latest # 刚才设置服务器runner的label
    permissions: # 设置jobs的权限
      contents: read
      id-token: write
    environment: "action" # 刚才设置secret的名称
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # 在secret设置的变量
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
    steps:
    - name: Checkout actions  # 拉代码
      uses: actions/checkout@v3
   # - name: Read Version # 读取版本号
   #    id: read_version
   #    run: |
   #     echo "BUILD_VERSION=$(node -p "require('./package.json').buildVersion")" >> $GITHUB_ENV
    - name: Docker Login # docker登录
      uses: docker/login-action@v1
      with:
        registry: registry.cn-heyuan.aliyuncs.com
        username: babaaliyum
        password: 123And45
    
    # - name: Setup Node
    #   uses: actions/setup-node@v2
    #   with:
    #      node-version: '16.18.0'

    # - name: Install Dependencies # 执行前端的安装脚本
    #   run: ./install.sh
      
    - name: Build # 打包并push镜像
      # env:
      #   DIRECTORY: test
      #   IMAGENAME: webapp-iamges
      #   REGISTRY: 1jfrog.io
      run: |
        # npm run prod:build
        # docker build . -t $IMAGENAME
        docker build -f Dockerfile -t docsify .
        docker tag docsify registry.cn-heyuan.aliyuncs.com/jiabinli/docsify:1.0.0
        docker push registry.cn-heyuan.aliyuncs.com/jiabinli/docsify:1.0.0

            # - name: Install webapp # 安装服务
            #   run: |
            #     sed -i 's/appVersion:.*/appVersion: \"${{ env.BUILD_VERSION }}\"/' /home/code/helms/webapp/iso/helm/webapp/Chart.yaml
            #     cd /home/code/helms/webapp/iso
            #     ./installWeb.sh

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: 8.155.16.54
        username: root
        password: 123And45
        port: 22
        script: cd ~  && echo "chao" && ls \
                && docker login --username=babaaliyum registry.cn-heyuan.aliyuncs.com  \
                && docker pull registry.cn-heyuan.aliyuncs.com/jiabinli/docsify:1.0.0 \
                && docker run -itp 3000:3000 --name=docsify -v $(pwd):/docs registry.cn-heyuan.aliyuncs.com/jiabinli/docsify:1.0.0
                
    - name: start for build Docsify 
      env: 
        START_STR: Hi there! My name is
        USER_NAME: Ber
        END_STR: Thank you
      run: |
        echo $START_STR $USER_NAME $END_STR.
